# -*- coding: utf-8 -*-
"""3tratamiento_b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aVbU3tY07Q6DytBB27hZWXWWBe6TKRjr
"""

import cv2 as cv
from google.colab.patches import cv2_imshow
# local cv.imshow,   parche reemplaza cv2_imshow

im1=cv.imread('/content/imagen1.jfif')
cv2_imshow(im1)
im2=cv.imread('/content/imagen2.png')
cv2_imshow(im2)

import numpy as np
import matplotlib.pyplot as plt
im=np.ones((500,500,3),dtype=np.uint8)*0
im[1:100,1:100,1]=250
im[:,:,2]=250
cv2_imshow(im)

MR=cv.getRotationMatrix2D((0,125),-30,1)
imR=cv.warpAffine(im1,MR,(250,250))
cv2_imshow(imR)

im3=cv.imread('/content/imagen3.jfif')
cv2_imshow(im3)

kernel=np.array([[1/9,1/9,1/9],[1/9,1/9,1/9],[1/9,1/9,1/9]])
im4=cv.filter2D(im3,-1,kernel)
cv2_imshow(im4)

kernel=np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]])
im5=cv.filter2D(im3,-1,kernel)
cv2_imshow(im5)

kernel=np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]])
im6=cv.filter2D(im3,-1,-kernel)
cv2_imshow(im6)

kernel=np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])
im7=cv.filter2D(im3,-1,kernel)
collage=np.hstack((im3,im4,im5,im6,im7))
cv2_imshow(collage)

kernel=np.array([[1,2,1],[2,4,2],[1,2,1]])
im8=cv.filter2D(im3,-1,1/16*kernel)
collage=np.hstack((im3,im4,im5,im6,im7))
cv2_imshow(im8)